<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/product/product.proto

namespace GPBMetadata\Proto\Product;

class Product
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            '
ç
proto/product/product.protoproductgoogle/protobuf/timestamp.proto"ß
Product

id (
name (	
description (	
price (.

created_at (2.google.protobuf.Timestamp.

updated_at (2.google.protobuf.Timestamp"-
ProductList
data (2.product.Product"H
ProductCreateRequest
name (	
description (	
price ("#
ProductFindOneRequest

id ("T
ProductUpdateRequest

id (
name (	
description (	
price (""
ProductDeleteRequest

id (2√
ProductService7
FindAll.google.protobuf.Empty.product.ProductList;
FindOne.product.ProductFindOneRequest.product.Product9
Create.product.ProductCreateRequest.product.Product?
Update.product.ProductUpdateRequest.google.protobuf.Empty?
Delete.product.ProductDeleteRequest.google.protobuf.EmptyB4Z%davilakey.com/davilakey/proto/product 
Pb\\Productbproto3'
        , true);

        static::$is_initialized = true;
    }
}

